### ISSUE TITLE
Create a pleasant developer workflow experience

### ISSUE THREAD

**Issue by awgreene** [operator-framework/rukpak#602]
A bit of a catch-all for issues related to creating a good developer experience. 

**Brainstorming:**

- [x] Create a PR template that defines what steps a reviewer should take | Completed in https://github.com/operator-framework/operator-controller/pull/124
--Check for unit or e2e tests.
-- API Documentation
-- Commits are prefixed with one of (Bug Fix, Feature, Doc). [Example](https://github.com/kubernetes-sigs/controller-runtime/blob/master/.github/workflows/verify.yml).
-- Commits properly convey what changes are being introduced.
-- Format is left to the contributor's and reviewer's discretion.
-- Commits are signed (`git commit --signoff`) | Completed by enabling DCO in the repo
--- Why do we need this?
---- https://github.com/cncf/foundation/blob/main/dco-guidelines.md
---- https://drewdevault.com/2021/04/12/DCO.html

**Create a Makefile**
-Consistent across projects.
-  RukPak's existing Makefile should be referenced when generating this list.
-- Existing makefile targets should be re-evaluated.
-- The Makefile and GitHub workflows should first be implemented in RukPak and then mirrored in the other projects.
- Standardize the developer experience across Deppy, RukPak, and Operator-Controller.
- [x] Running `make` prints out available targets. | Changed to `make help`, [completed](https://github.com/operator-framework/operator-controller/blob/520219c1c4812d3446c85cf8383de3572ebbbf9d/Makefile#L35-L48)
- [x] `run`: If applicable, spins up a kind cluster and runs the container. | [Completed](https://github.com/operator-framework/operator-controller/blob/520219c1c4812d3446c85cf8383de3572ebbbf9d/Makefile#L100-L101)
- [x] `test-e2e`: Runs a set of e2e tests. | [Completed](https://github.com/operator-framework/operator-controller/blob/520219c1c4812d3446c85cf8383de3572ebbbf9d/Makefile#L73-L74)
- [x] `test-unit`: Runs a set of unit tests. | [Completed](https://github.com/operator-framework/operator-controller/blob/520219c1c4812d3446c85cf8383de3572ebbbf9d/Makefile#L78-L79)

-  RukPak's existing Makefile should be referenced when generating this list.
-- Existing makefile targets should be re-evaluated.
-- The Makefile and GitHub workflows should first be implemented in RukPak and then mirrored in the other projects.
- Standardize the developer experience across Deppy, RukPak, and Operator-Controller.

**Nice to have:**
- Support remote debugging.
- The version of the Go compiler is loosely enforced by the go.mod file's go compatibility version, and we have the github actions configured to use the go version aligned with the go.mod file.

**Comment by joelanford** [comment]
Context: Rukpak has a relatively good developer experience, and we want to use it as a model for the other OLMv1 repositories. With that in mind, this task is about making whatever adjustments (if any) that are necessary to make Rukpak's setup a model we can replicate in other projects.

Some of the thoughts in the description are already happening in rukpak. For those, are there any improvements we could make?

On this list, what are must-haves and what are nice-to-haves?
